import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

const routes=[
    {
      path: '/Homepage',
      name:'Homepage',
      component(resolve){
        require(['../components/Homepage.vue'],resolve)
      }
    },
    {
      path: '/home',
      name:'home',
      component(resolve){
        require(['../components/home.vue'],resolve)
      }
    },
    {
      path: '/publicNumber',
      name:'publicNumber',
      component(resolve){
        require(['../components/publicNumber.vue'],resolve)
      }
    },
    {
      path: '/publicNumberTwo',
      name:'publicNumberTwo',
      component(resolve){
        require(['../components/publicNumberTwo.vue'],resolve)
      }
    },
    {
      path:'/loanProducts',
      name:'loanProducts',
      component(resolve){
        require(['../components/loanProducts.vue'],resolve)
      }
    },
    {
      path:'/loan',
      name:'loan',
      component(resolve){
        require(['../components/loan.vue'],resolve)
      }
    },
    {
      path:'/consultation',
      name:'consultation',
      component(resolve){
        require(['../components/consultation.vue'],resolve)
      }
    },
    {
      path:'/agreement',
      name:'agreement',
      component(resolve){
        require(['../pages/agreement.vue'],resolve)
      }
    },
    {
      path:'/productDetail',
      name:'productDetail',
      component(resolve){
        require(['../components/productDetail.vue'],resolve)
      }
    },
    {
      path:'/products',
      name:'products',
      component(resolve){
        require(['../components/products.vue'],resolve)
      }
    },
    {
      path:'/product',
      name:'product',
      component(resolve){
        require(['../components/product.vue'],resolve)
      }
    },
    {
      path:'/recommendProduct',
      name:'recommendProduct',
      component(resolve){
        require(['../components/recommendProduct.vue'],resolve)
      }
    },
    {
      path:'/pop',
      name:'pop',
      component(resolve){
        require(['../components/pop.vue'],resolve)
      }
    },
    {
      path:'/selfPop',
      name:'selfPop',
      component(resolve){
        require(['../components/selfPop.vue'],resolve)
      }
    },
    {
      path:'/mine',
      name:'mine',
      component(resolve){
        require(['../components/mine.vue'],resolve)
      }
    },
    {
      path:'/login',
      name:'login',
      component(resolve){
        require(['../components/login.vue'],resolve)
      }
    },
    {
      path:'/regist',
      name:'regist',
      component(resolve){
        require(['../components/regist.vue'],resolve)
      }
    },
    {
      path:'/index',
      name:'index',
      component(resolve){
        require(['../components/index.vue'],resolve)
      }
    },
    {
      path:'/personalInfo',
      name:'personalInfo',
      component(resolve){
        require(['../components/personalInfo.vue'],resolve)
      }
    },
    {
      path:'/forgetPsd',
      name:'forgetPsd',
      component(resolve){
        require(['../components/forgetPsd.vue'],resolve)
      }
    },
    {
      path:'/wxdPromotion',
      name:'wxdPromotion',
      component(resolve){
        require(['../pages/wxdPromotion'],resolve)
      }
    },
    {
      path:'/changePhoto',
      name:'changePhoto',
      component(resolve){
        require(['../components/changePhoto'],resolve)
      }
    },
    {
      path:'/thirdPage',
      name:'thirdPage',
      component(resolve){
        require(['../pages/thirdPage'],resolve)
      }
    },
    {
      path:'/download',
      name:'download',
      component(resolve){
        require(['../components/download'],resolve)
      }
    },
    {
      path:'/iosDownload',
      name:'iosDownload',
      component(resolve){
        require(['../components/iosDownload'],resolve)
      }
    },
    {
      path:'/signUp',
      name:'signUp',
      component(resolve){
        require(['../pages/signUp'],resolve)
      }
    },
    {
      path: '/',
      redirect: '/Homepage'
    }
]
export default new Router({
  routes
})

export const routerState = {
  previous: null
}
